name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH key for authentication
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      # Set up known hosts to avoid SSH prompt
      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.200.215.77 >> ~/.ssh/known_hosts

      # SSH into EC2 and deploy
      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/my-ec2-key.pem ec2-user@13.200.215.77 << 'EOF'
            cd /path/to/your/app
            docker-compose down
            docker-compose up -d
          EOF

