

version: '3.8'

services:
  mydb:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mydb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
      MYSQL_DATABASE: school

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "3500:3500"
    depends_on:
      - mydb
    env_file:
      - ./backend/.env

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    env_file:
      - ./frontend/.env

volumes:
  db_data:
