services:
  mydb:
    build:
      context: ../database
      dockerfile: Dockerfile
    container_name: mydb
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: mysql123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    container_name: backend
    build: ./backend
    environment:
      - ./backend/.env
    ports:
      - "5000:5000"
    depends_on:
      - mydb

  frontend:
    container_name: frontend
    build: ./frontend
    environment:
      - ./backend/.env
    ports:
      - "5173:5173"

volumes:
  db_data:

