version: '3.8'

services:
  mydb:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: mydb
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  backend:
    container_name: backend
    build: ./backend
    environment:
      - ./backend/.env
    ports:
      - "3500:3500"
    depends_on:
      - mydb

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  db_data:
