version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DB_HOST=mydb
      - DB_USER=root
      - DB_PASSWORD=mysql123
      - DB_NAME=school
    ports:
      - "3500:3500"
    depends_on:
      - mydb

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  mydb:
    image: mysql:latest
    container_name: mydb
    environment:
      - MYSQL_ROOT_PASSWORD=mysql123  # Ensure the root password is set here
      - MYSQL_DATABASE=school  # Make sure the database is set
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
